name: finki-discord-bot-dev

services:
  bot:
    build: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      TOKEN: ${TOKEN}
      APPLICATION_ID: ${APPLICATION_ID}
      DATABASE_URL: ${DATABASE_URL}
      CHATBOT_URL: ${CHATBOT_URL}
      TZ: ${TZ}
    image: finki-discord-bot-dev:latest
    networks:
      - finki_stack_dev
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./logs:/app/logs

  database:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      interval: 15s
      retries: 3
      start_period: 5s
      test:
        - "CMD-SHELL"
        - "pg_isready -U $$POSTGRES_USER"
      timeout: 30s
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - finki_stack_dev
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    networks:
      - finki_stack_dev
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./pgadmin:/var/lib/pgadmin

networks:
  finki_stack_dev:
    name: finki_stack_dev
    driver: bridge
    external: true
