name: finki-discord-bot
services:
  bot:
    container_name: bot
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    image: delemangi/finki-discord-bot:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./logs:/app/logs
  database:
    container_name: db
    env_file:
      - .env
    healthcheck:
      interval: 15s
      retries: 3
      start_period: 5s
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U $$POSTGRES_USER'
      timeout: 30s
    image: postgres:17
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
