name: finki-discord-bot

services:
  database:
    container_name: finki-database
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

  bot:
    container_name: finki-bot
    image: delemangi/finki-discord-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./bot.log:/app/bot.log
