name: finki-discord-bot-dev
services:
  bot:
    build: .
    container_name: bot
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    image: finki-discord-bot-dev:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./logs:/app/logs
  database:
    container_name: db
    env_file:
      - .env
    healthcheck:
      interval: 15s
      retries: 3
      start_period: 5s
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U $$POSTGRES_USER'
      timeout: 30s
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    image: dpage/pgadmin4:latest
    ports:
      - '5050:80'
    restart: unless-stopped
    user: '$UID:$GID'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
