name: Feature request
description: Request a new feature
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: I'm always frustrated when..., Discord has recently released..., A good addition would be...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or similar that will help us.
