name: Question
description: Ask a question
labels:
  - question
body:
  - type: textarea
    id: issue-description
    attributes:
      label: What is your question?
      description: Please try to be as clear and concise as possible.
    validations:
      required: true
