version: "3.8"

services:
  container:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: finki-discord-bot-dev:latest
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ..:/app
      - /app/node_modules
    user: root

  database:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
