export const commands = {
  about: 'Информации за ботот',
  anto: 'Анто факт',
  calendar: 'Академски календар',
  classroom: 'Информации за простории',
  'course info': 'Информации за предмети',
  'course participants': 'Број на слушатели на предмети',
  'course prerequisite': 'Предуслови за предмети',
  'course professors': 'Наставен кадар на предмети',
  'course role': 'Број на корисници во канали на предмети',
  'course summary': 'Сите информации за предмети',
  'courses prerequisite': 'Сите предмети според предуслов',
  'courses programs': 'Сите предмети според смер',
  crosspost: 'Вклучи или исклучи crossposting',
  embed: 'Креирај ембед',
  faq: 'Најчесто поставувани прашања',
  help: 'Помош за командите',
  home: 'Изворен код на ботот',
  invite: 'Пристапен линк до серверот',
  link: 'Најчесто барани линкови',
  'list links': 'Листа од сите линкови',
  'list questions': 'Листа од сите прашања',
  members: 'Број на членови на серверот',
  ping: 'Пинг на ботот',
  'poll add': 'Додади опции на анкети',
  'poll anonymous': 'Измени анонимност на анкети',
  'poll create': 'Креирај анкети',
  'poll delete': 'Избриши анкети',
  'poll edit': 'Измени наслов и опис на анкети',
  'poll open': 'Измени пристап на анкети',
  'poll remove': 'Избриши опции на анкети',
  'poll show': 'Прикажи анкети',
  'poll stats': 'Статистика за анкети',
  profile: 'Информации за студенти',
  purge: 'Бриши пораки',
  quiz: 'Започни го квизот Кој Сака Да Биде Морален Победник',
  reminder: 'Потсетник',
  session: 'Распоред за испитни сесии и колоквиуми',
  staff: 'Информации за професори',
  'statistics activity': 'Статистика за улогите за активности',
  'statistics color': 'Статистика за улогите за бои',
  'statistics course': 'Статистика за улогите за предмети',
  'statistics notification': 'Статистика за улогите за нотификации',
  'statistics program': 'Статистика за улогите за програми',
  'statistics year': 'Статистика за улогите за години',
  timetable: 'Распоред на часови'
};

export const programMapping: { [index in ProgramKeys]: ProgramValues } = {
  ИМБ: 'imb',
  КЕ: 'ke',
  КИ: 'ki',
  КН: 'kn',
  ПИТ: 'pit',
  СИИС: 'siis'
};
